//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_SQL_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment_PropertiesApartment
    {
        public int Id_apartment { get; set; }
        public int Id_propertiesApartment { get; set; }
        public string ValueProperties { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual PropertiesApartment PropertiesApartment { get; set; }
    }
}
