//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_SQL_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoApartment
    {
        public int Id_photo { get; set; }
        public byte[] Name { get; set; }
        public int Id_apartment { get; set; }
        public int Id_firm { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Firm Firm { get; set; }
    }
}
