//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_SQL_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertiesApartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertiesApartment()
        {
            this.Apartment_PropertiesApartment = new HashSet<Apartment_PropertiesApartment>();
            this.TypeApartments = new HashSet<TypeApartment>();
        }
    
        public int Id_propertiesApartment { get; set; }
        public string NameProperties { get; set; }
        public string TypeProperties { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apartment_PropertiesApartment> Apartment_PropertiesApartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeApartment> TypeApartments { get; set; }
    }
}
