//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_SQL_ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VolgInfoDBEntities : DbContext
    {
        public VolgInfoDBEntities()
            : base("name=VolgInfoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Apartment> Apartments { get; set; }
        public virtual DbSet<Changelog> Changelogs { get; set; }
        public virtual DbSet<ChangelogAgent> ChangelogAgents { get; set; }
        public virtual DbSet<Firm> Firms { get; set; }
        public virtual DbSet<PhotoApartment> PhotoApartments { get; set; }
        public virtual DbSet<PropertiesApartment> PropertiesApartments { get; set; }
        public virtual DbSet<TypeApartment> TypeApartments { get; set; }
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Apartment_PropertiesApartment> Apartment_PropertiesApartment { get; set; }
    }
}
