//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RieltorBase.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public int PasswordId { get; set; }
        public int AgentId { get; set; }
        public string Login { get; set; }
        public string Password1 { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
