//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RieltorBase.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int PhotoId { get; set; }
        public Nullable<int> RealtyObjectId { get; set; }
        public Nullable<int> FirmId { get; set; }
        public string RelativeSource { get; set; }
    
        public virtual Firm Firm { get; set; }
        public virtual RealtyObject RealtyObject { get; set; }
    }
}
