//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RieltorBase.Domain
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    using MetadataInfo;

    /// <summary>
    /// Контекст базы данных недвижимости.
    /// </summary>
    public partial class VolgaInfoDBEntities : DbContext
    {
        public VolgaInfoDBEntities()
            : base("name=VolgaInfoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Changelog> Changelogs { get; set; }
        public virtual DbSet<ChangelogAgent> ChangelogAgents { get; set; }
        public virtual DbSet<Firm> Firms { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<PropertyType> PropertyTypes { get; set; }
        public virtual DbSet<PropertyValue> PropertyValues { get; set; }
        public virtual DbSet<RealtyObject> RealtyObjects { get; set; }
        public virtual DbSet<RealtyObjectType> RealtyObjectTypes { get; set; }

        /// <summary>
        /// Полная очистка базы данных.
        /// </summary>
        public void ClearDatabase()
        {
            this.DeleteLog();
            this.DeleteMainData();
            this.DeleteMetadata();
        }

        /// <summary>
        /// Создать стандартные метаданные.
        /// </summary>
        public void CreateStandardMetadata()
        {
            foreach (TypeMetadataDescription typeDescription
                in Metadata.GetInstance().TypeDescriptions)
            {
                RealtyObjectType newType = 
                    new RealtyObjectType();

                newType.TypeName = typeDescription.Name;

                foreach (string propName 
                    in typeDescription.PropertyNames)
                {
                    PropertyType propType = 
                        this.FindOrCreatePropertyType(propName);
                    newType.PropertyTypes.Add(propType);
                }

                this.RealtyObjectTypes.Add(newType);
            }
        }

        /// <summary>
        /// Создать несколько тестовых объектов в БД.
        /// </summary>
        public void CreateFewObjects()
        {
            // фирмы и агенты
            Firm newFirm = this.Firms.Add(new Firm()
            {
                Name = "Фирма \"У Васи\""
            });

            Agent vasya = this.Agents.Add(new Agent()
            {
                Firm = newFirm,
                Name = "Вася",
                IsFirmAdmin = true,
                Addres = "Ленина 25",
                LastName = "Пупкин",
                PhoneNumber = "33 - 33-3(0)"
            });

            // квартиры
            RealtyObject vasyasAppartment1 = this.RealtyObjects.Add(new RealtyObject()
            {
                RealtyObjectType = this.RealtyObjectTypes
                    .First(type => type.TypeName == "Квартиры"),
                Agent = vasya
            });

            new List<PropertyValue>(new []
            {
                new PropertyValue()
                {
                    PropertyType = this.PropertyTypes.First(prType => prType.PropertyName == "Дата"),
                    StringValue = "11/05/2016"
                }, 
                new PropertyValue()
                {
                    PropertyType = this.PropertyTypes.First(prType => prType.PropertyName == "Улица"),
                    StringValue = "Ленина"
                }, 
                new PropertyValue()
                {
                    PropertyType = this.PropertyTypes.First(prType => prType.PropertyName == "Дом"),
                    StringValue = "11"
                }, 
                new PropertyValue()
                {
                    PropertyType = this.PropertyTypes.First(prType => prType.PropertyName == "Цена тыс.руб."),
                    StringValue = "1100"
                }, 
                new PropertyValue()
                {
                    PropertyType = this.PropertyTypes.First(prType => prType.PropertyName == "Дополнительная информация"),
                    StringValue = "Вся мебель остается"
                }
            })
            .ForEach(value => vasyasAppartment1.PropertyValues.Add(value));

            RealtyObject vasyasAppartment2 = this.RealtyObjects.Add(new RealtyObject()
            {
                RealtyObjectType = this.RealtyObjectTypes
                    .FirstOrDefault(type => type.TypeName == "Квартиры"),
                Agent = vasya
            });

            new List<PropertyValue>(new[]
            {
                new PropertyValue()
                {
                    PropertyType = this.PropertyTypes.First(prType => prType.PropertyName == "Дата"),
                    StringValue = "11/05/2016"
                }, 
                new PropertyValue()
                {
                    PropertyType = this.PropertyTypes.First(prType => prType.PropertyName == "Улица"),
                    StringValue = "Ленина"
                }, 
                new PropertyValue()
                {
                    PropertyType = this.PropertyTypes.First(prType => prType.PropertyName == "Дом"),
                    StringValue = "11"
                }, 
                new PropertyValue()
                {
                    PropertyType = this.PropertyTypes.First(prType => prType.PropertyName == "Цена тыс.руб."),
                    StringValue = "1100"
                }, 
                new PropertyValue()
                {
                    PropertyType = this.PropertyTypes.First(prType => prType.PropertyName == "Дополнительная информация"),
                    StringValue = "Вся мебель остается"
                }
            })
            .ForEach(value => vasyasAppartment2.PropertyValues.Add(value));
        }

        /// <summary>
        /// Удалить записи журнала.
        /// </summary>
        private void DeleteLog()
        {
            this.Actions.RemoveRange(this.Actions);
            this.Changelogs.RemoveRange(this.Changelogs);
            this.ChangelogAgents.RemoveRange(this.ChangelogAgents);
        }

        /// <summary>
        /// Удалить основные данные: информацию об объектах недвижимости, фирмах и агентах.
        /// </summary>
        private void DeleteMainData()
        {
            this.Photos.RemoveRange(this.Photos);
            this.PropertyValues.RemoveRange(this.PropertyValues);
            this.RealtyObjects.RemoveRange(this.RealtyObjects);
            this.Agents.RemoveRange(this.Agents);
            this.Firms.RemoveRange(this.Firms);
        }

        /// <summary>
        /// Удалить информацию о типах и свойствах. 
        /// </summary>
        private void DeleteMetadata()
        {
            this.RealtyObjectTypes.RemoveRange(this.RealtyObjectTypes);
            this.PropertyTypes.RemoveRange(this.PropertyTypes);
        }

        /// <summary>
        /// Найти, или добавить новый тип свойства.
        /// </summary>
        /// <param name="propName">Имя свойства.</param>
        private PropertyType FindOrCreatePropertyType(string propName)
        {
            PropertyType existingType = 
                this.PropertyTypes.Local.FirstOrDefault(
                    prType => prType.PropertyName == propName)
                ?? this.PropertyTypes.FirstOrDefault(
                    prType => prType.PropertyName == propName);

            if (existingType != null)
            {
                return existingType;
            }

            PropertyType newPropType = new PropertyType()
            {
                PropertyName = propName,
                PropertyValueType = "String"
            };

            this.PropertyTypes.Add(newPropType);
            return newPropType;
        }
    }
}
