//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealtyObject
    {
        public RealtyObject()
        {
            this.Photos = new HashSet<Photo>();
            this.PropertyValues = new HashSet<PropertyValue>();
        }
    
        public int RealtyObjectId { get; set; }
        public int RealtyObjectTypeId { get; set; }
        public Nullable<int> AgentId { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual ICollection<PropertyValue> PropertyValues { get; set; }
        public virtual RealtyObjectType RealtyObjectType { get; set; }
    }
}
